# Generated by Django 6.0.3 on 2026-03-22 17:03

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(help_text='Maximum file size allowed is 5MB. Only PDF.', upload_to='resumes/', validators=[api.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('resume_content', models.TextField()),
                ('job_url', models.URLField(blank=True, max_length=500, null=True)),
                ('job_content', models.TextField(blank=True, null=True)),
                ('job_skills', models.JSONField(blank=True, default=list)),
                ('count_job_skills', models.PositiveIntegerField(default=0)),
                ('cv_skills', models.JSONField(blank=True, default=list)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('count_match_skills', models.PositiveIntegerField(default=0)),
                ('skills_to_learn', models.JSONField(blank=True, default=list)),
                ('count_skills_to_learn', models.PositiveIntegerField(default=0)),
                ('overall_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage score from 0 to 100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
